version: '3'
services:
  server:
    build:
      context: ./server  
    ports:
      - "5000:5000"    
    volumes:
      - ./server:/app   
    depends_on:
      - client          

  client:
    build:
      context: ./templates/client 
    ports:
      - "8080:80"         
